seed_paper_ids: # list of seed papers to graph traverse: can be arxiv or doi or scholar ID: Note the below are all the same paper
  - a2ce1fb96c0b78bee18bb2cb2c3d55dc48d54cbd # example scholar ID Kurita 2019
  - 10.18653/v1/2021.acl-long.416 # stereoset
  - 10.18653/v1/2020.emnlp-main.154 # crows-pairs
  - 10.18653/v1/2020.findings-emnlp.301 # toxicity prompts
  - arXiv:1911.03064 # huang 2019
  - arXiv:2005.00614 # dinan 2020
  - arXiv:1909.01326 # sheng 2019
  - 10.18653/v1/N19-3002 # bordia and bowman 2019
  #- arXiv:1906.07337 # example arxiv ID
  #- 10.18653/v1/2020.acl-main.468" # example DOI
only_include_sections: # TODO confirm full set, only seen methodology, result, and background
  - methodology
  - result
only_influential: False # bool True false for filtering by influential papers
output_dir: results/


